version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticketing_postgres
    environment:
      POSTGRES_USER: ticketing_user
      POSTGRES_PASSWORD: ticketing_password
      POSTGRES_DB: ticketing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketing_user -d ticketing_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://ticketing_user:ticketing_password@postgres:5432/ticketing_db
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
